title: Miguel A. González Ballester
position: ICREA Professor
affiliation: Universitat Pompeu Fabra
email: ma.gonzalez (at) upf.edu
keywords: computer vision image processing medical imaging
google_scholar: https://scholar.google.com/citations?user=FmU4pM0AAAAJ
github_link: https://github.com/magonballester
linkedin: https://www.linkedin.com/in/miguelangelgonzalez/
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Miguel A. González Ballester
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
